language: python
python:
 - "3.6"
install:
 - pip install codecov
 - pip install pytest-cov
script:
 - pip install -e .
 - pip install -e .[test]
 - flake8 --show-source pynga/
 - py.test tests/ --cov=./pynga/
after_success:
 - codecov
