language: python
python:
 - "3.6"
install:
 - pip install -r ./requirements.txt
 - pip install flake8
 - pip install codecov
 - pip install pytest-cov
script:
 - flake8 --show-source pynga
 - py.test --cov=./
after_success:
 - codecov
